---
ungrouped:
  hosts:
    leela:
    morbo:
hw_nibbler:
  hosts:
    nibbler:
    vm0.nibbler:
    pfsense.nibbler:
ntp_clients:
  hosts:
    farnsworth:
    nibbler:
    vm0.nibbler:
etc_hosts:
  hosts:
    scruffy:
    farnsworth:
    nibbler:
    vm0.nibbler:
    pfsense.nibbler:
eth_netplan:
  hosts:
    scruffy:
    vm0.nibbler:
eth_ifupdown:
  hosts:
    nibbler:
docker:
  hosts:
    scruffy:
    vm0.nibbler:
nameservers:
  hosts:
    scruffy:
    vm0.nibbler:
pve:
  hosts:
    nibbler:
