---
roles:
  - name: openstack.chrony
    src: https://github.com/openstack/ansible-role-chrony
    version: 1.3.0
  - name: geerlingguy.ntp
    version: 2.5.0
  - name: geerlingguy.pip
    version: 3.0.3
  - name: geerlingguy.docker
    version: 7.3.0
  - name: geerlingguy.certbot
    version: 5.1.0
  - name: mrlesmithjr.netplan
    version: v0.4.1
collections:
  - name: community.docker
    version: 3.10.4
  - name: community.general
    version: 9.1.0
  - name: lucasheld.uptime_kuma
    version: 1.2.0
  - name: ansible.posix
    version: 1.5.4
  - name: prometheus.prometheus
    version: 0.17.0
