---
- name: Networking
  import_playbook: playbooks/networking.yaml
- name: Proxmox
  import_playbook: playbooks/proxmox.yaml
- name: Docker
  import_playbook: playbooks/docker.yaml
- name: DNS
  import_playbook: playbooks/dns.yaml
- name: Time
  import_playbook: playbooks/time.yaml
- name: Certificates
  import_playbook: playbooks/certs.yaml
- name: Reverse proxy
  import_playbook: playbooks/reverse_proxy.yaml
- name: Metrics
  import_playbook: playbooks/metrics.yaml
- name: Uptime monitor
  import_playbook: playbooks/uptime.yaml
