---
- name: Make Nginx directory
  ansible.builtin.file:
    path: /etc/nginx
    state: directory
    mode: "0755"
- name: Generate configuration
  ansible.builtin.template:
    src: nginx-conf.jinja
    dest: /etc/nginx/{{ reverse_proxy_conf }}.conf
    mode: "0644"
  notify:
    - Reload Nginx
- name: Install Nginx
  community.docker.docker_container:
    name: "{{ reverse_proxy_name }}"
    image: nginx:latest
    networks: "{{ reverse_proxy_networks }}"
    published_ports:
      - 80/tcp
      - 443/tcp
    restart_policy: unless-stopped
    state: started
    volumes:
      - "{{ conf }}:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/nginx/certs:/etc/nginx/certs:ro"
  vars:
    conf: "/etc/nginx/{{ reverse_proxy_conf }}.conf"
