---
- name: Make Nginx directory
  ansible.builtin.file:
    path: /etc/nginx
    state: directory
    mode: "0755"
- name: Generate configuration
  ansible.builtin.template:
    src: nginx-conf.jinja
    dest: /etc/nginx/{{ reverse_proxy_conf }}.conf
    mode: "0644"
  notify:
    - Reload Nginx
- name: Install Nginx
  community.docker.docker_container:
    name: "{{ reverse_proxy_name }}"
    image: nginx:1.27.0
    image_name_mismatch: recreate
    networks:
      - name: "{{ reverse_proxy_network }}"
        ipv4_address: "{{ reverse_proxy_ip }}"
    dns_servers:
      - "{{ ip_dns_0 }}"
      - "{{ ip_dns_1 }}"
    published_ports:
      - 80/tcp
      - 443/tcp
    restart_policy: unless-stopped
    state: started
    volumes:
      - "{{ conf }}:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/nginx/certs:/etc/nginx/certs:ro"
      - "/var/log/nginx/:/var/log/nginx/"
  vars:
    conf: "/etc/nginx/{{ reverse_proxy_conf }}.conf"
