{
 "title": "Pi-hole",
 "description": "DNS metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(pihole_ads_blocked_today,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Primary Blocking Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_status{host=~'dns0'}", "legendFormat": "{{ legend }}" }
   ]
  },
  {
   "title": "DNS Queries (by node)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_dns_queries_all_types", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "% ads blocked",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pihole_ads_blocked_today{host=~'$node'})/sum(pihole_dns_queries_today{host=~'$node'})*100"
    }
   ]
  },
  {
   "title": "Secondary Blocking Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_status{host=~'dns1'}", "legendFormat": "{{ legend }}" }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(pihole_domains_being_blocked{host=~'$node'})"
    }
   ]
  },
  {
   "title": "Unique domains",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pihole_unique_domains{host=~'$node'})"
    }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pihole_dns_queries_all_types{host=~'$node'})",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (domain)(pihole_top_queries{host=~\"$node\"})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type)(pihole_reply{host=~'$node'})!=0",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (domain)(pihole_top_ads{host=~'$node'})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Ads blocked (today)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pihole_ads_blocked_today{host=~'$node'})",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Top queries",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "topk(15, sum by (domain)(pihole_top_queries{host=~\"$node\"}))",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(pihole_ads_blocked_today{host=~'$node'})/sum(pihole_dns_queries_today{host=~'$node'})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(15, sum by (domain)(pihole_top_ads{host=~\"$node\"}))",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Queries cached/forwarded",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pihole_queries_cached{host=~'$node'})",
     "legendFormat": "Queries cached"
    },
    {
     "expr": "sum(pihole_queries_forwarded{host=~'$node'})",
     "legendFormat": "Queries forwarded"
    }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (type)(pihole_querytypes{host=~\"$node\"} * on(host)group_left pihole_dns_queries_today{host=~\"$node\"}/100) !=0",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (destination)(pihole_forward_destinations{host=~\"$node\"} * on(host)group_left pihole_dns_queries_today{host=~\"$node\"}/100)",
     "legendFormat": "{{ destination }}"
    }
   ]
  },
  {
   "title": "Unique clients",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pihole_unique_clients{host=~'$node'})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}