{
 "title": "Flask Monitoring",
 "description": "Flask Monitoring with StatsD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(flask_exporter_info{},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nummus_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(flask_http_request_duration_seconds_sum{job=\"${app_name}\"} / flask_http_request_duration_seconds_count{job=\"${app_name}\"})",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (flask_http_request_total{job=\"$app_name\"})"
    },
    {
     "expr": "sum (flask_http_request_total{job=\"$app_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (flask_http_request_total{job=\"$app_name\"}) by(status)",
     "legendFormat": "HTTP Status: {{status}}"
    },
    {
     "expr": "sum (flask_http_request_total{job=\"$app_name\"}) by(status)",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{job=\"$app_name\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{job=\"${app_name}\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{job=\"$app_name\", status=~\"2.*\"}) by(path, method) / sum(flask_http_request_total{job=\"$app_name\"}) by(path, method)",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{job=\"$app_name\", status=~\"5.*\"}) by(path, method) / sum(flask_http_request_total{job=\"$app_name\"}) by(path, method)",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum{job=\"$app_name\"} / flask_http_request_duration_seconds_count{job=\"$app_name\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Duration Distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(flask_http_request_duration_seconds_bucket{job=\"$app_name\"}[$__range])) by (path, le)) >= 0"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(flask_http_request_duration_seconds_bucket{job=\"$app_name\"}[$__range])) by (path, le)) >= 0"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(flask_http_request_duration_seconds_bucket{job=\"$app_name\"}[$__range])) by (path, le)) >= 0"
    }
   ]
  }
 ]
}