{
 "title": "Time",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "NTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Chrony offset",
   "type": "stat",
   "description": "Estimated offset of the NTP time",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chrony_tracking_last_offset_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RMS offset",
   "type": "stat",
   "description": "This is a long-term average of the offset value",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chrony_tracking_rms_offset_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root dispersion",
   "type": "stat",
   "description": "This is the total dispersion accumulated through all the paths to the root time server",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chrony_tracking_root_dispersion_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skew",
   "type": "stat",
   "description": "This is the estimated error bound on the frequency",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chrony_tracking_skew_ppms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "description": "This is the frequency offset between the RTC and reference clock",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chrony_tracking_frequency_ppms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Residual frequency",
   "type": "stat",
   "description": "This is the frequency offset between the frequency the reference suggests and the one currently in use",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chrony_tracking_residual_frequency_ppms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chrony offset",
   "type": "timeseries",
   "description": "Estimated offset of the NTP time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_tracking_last_offset_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RMS offset",
   "type": "timeseries",
   "description": "This is a long-term average of the offset value",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_tracking_rms_offset_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root dispersion",
   "type": "timeseries",
   "description": "This is the total dispersion accumulated through all the paths to the root time server",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "chrony_tracking_root_dispersion_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skew",
   "type": "timeseries",
   "description": "This is the estimated error bound on the frequency",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "chrony_tracking_skew_ppms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "description": "This is the frequency offset between the RTC and reference clock",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "chrony_tracking_frequency_ppms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Residual frequency",
   "type": "timeseries",
   "description": "This is the frequency offset between the frequency the reference suggests and the one currently in use",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "chrony_tracking_residual_frequency_ppms",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}