---
- name: Reload systemd
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Restart nummus
  become: true
  ansible.builtin.service:
    name: nummus.service
    enabled: true
    state: restarted
