---
# scruffy needs hostnames to bare metal in order to ssh to them
- name: Generate /etc/hosts file on scruffy
  hosts: scruffy
  roles:
    - role: etc_hosts
      etc_hosts_list: "{{ groups['etc_hosts'] }}"
- name: Setup nameservers
  hosts: nameservers
  roles:
    - role: pihole
      become: true
      pihole_hostname: "{{ is_dns_primary | ternary('pihole0', 'pihole1')}}"
      pihole_domain: "{{ domain_lan }}"
      pihole_password: "{{ pihole_admin_password }}"
      pihole_network: "{{ 'vlan-' + vlan_networking.name }}"
      pihole_ip: "{{ is_dns_primary | ternary(ip_dns_0, ip_dns_1) }}"
      pihole_dhcp_subnet: "10.0.0.0/8"
      pihole_dhcp_server: "{{ vlan_networking.ip }}.1"
      pihole_wildcard:
        - domain: "{{ domain_lan }}"
          ip: "{{ ip_reverse_proxy }}"
      pihole_extra_hosts:
        - host: direct.dns0
          ip: "{{ ip_dns_0 }}"
        - host: direct.dns1
          ip: "{{ ip_dns_1 }}"
        - host: ntp
          ip: "{{ ip_ntp_server }}"
