---
- name: Setup interfaces with netplan
  hosts: eth_netplan
  roles:
    - role: netplan_vlan
      netplan_vlan_vlans: "{{ vlans }}"
      netplan_vlan_mac: "{{ eth_services_mac }}"
      netplan_vlan_extra_eths: "{{ vlans_extras | default({}) }}"
      netplan_vlan_dns_addresses:
        - "{{ ip_dns_0 }}"
        - "{{ ip_dns_1 }}"
      netplan_vlan_domain: "{{ domain_lan }}"
      netplan_vlan_hw_offload: "{{ vlan_hw_offload | default(true) }}"
- name: Setup nameservers
  hosts: nameservers
  roles:
    - role: pihole
      become: true
      pihole_hostname: "{{ is_dns_primary | ternary('pihole0', 'pihole1')}}"
      pihole_domain: "{{ domain_lan }}"
      pihole_password: "{{ pihole_admin_password }}"
      pihole_network: "{{ 'vlan-' + vlan_networking.name }}"
      pihole_ip: "{{ is_dns_primary | ternary(ip_dns_0, ip_dns_1) }}"
      pihole_dhcp_subnet: "10.0.0.0/8"
      pihole_dhcp_server: "{{ vlan_networking.ip }}.1"
      pihole_wildcard:
        - domain: "{{ domain_lan }}"
          ip: "{{ ip_reverse_proxy }}"
      pihole_extra_hosts:
        - host: dns0
          ip: "{{ ip_dns_0 }}"
        - host: dns1
          ip: "{{ ip_dns_1 }}"
        - host: ntp
          ip: "{{ ip_ntp_server }}"
