---
- name: Install reverse proxy
  hosts: vm0.nibbler
  roles:
    - role: reverse_proxy
      become: true
      reverse_proxy_network: "{{ 'vlan-' + vlan_networking.name }}"
      reverse_proxy_ip: "{{ ip_reverse_proxy }}"
      reverse_proxy_exporter_network: "{{ 'vlan-' + vlan_management.name }}"
      reverse_proxy_exporter_ip: "{{ ip_reverse_proxy_exporter }}"
      reverse_proxy_wildcard: "{{ domain_lan }}"
      reverse_proxy_conf: private
      reverse_proxy_services:
        - name: dns
          ip: "{{ ip_dns_0 }}"
          suffix: "/admin"
          server_extra: rewrite ^/admin/?(.*)$ /$1 permanent;
        - name: dns0
          ip: "{{ ip_dns_0 }}"
          suffix: "/admin"
          server_extra: rewrite ^/admin/?(.*)$ /$1 permanent;
        - name: dns1
          ip: "{{ ip_dns_1 }}"
          suffix: "/admin"
          server_extra: rewrite ^/admin/?(.*)$ /$1 permanent;
        # morbo is WAP and requires special headers to talk through proxy
        - name: morbo
          ip: "{{ hostvars['morbo'].ip_management }}"
          scheme: https
          port: 443
          header_host: "{{ hostvars['morbo'].ip_management }}"
        - name: leela
          ip: "{{ hostvars['leela'].ip_management }}"
          scheme: https
          port: 443
        - name: uptime
          ip: "{{ ip_uptime }}"
          port: 3001
        - name: prometheus
          ip: "{{ ip_prometheus }}"
          port: 9090
        - name: alertmanager
          ip: "{{ ip_alertmanager }}"
          port: 9093
        - name: grafana
          ip: "{{ ip_grafana }}"
          port: 3000
        - name: dns0-exporter
          ip: "{{ ip_dns_exporter_0 }}"
          port: 9617
        - name: dns1-exporter
          ip: "{{ ip_dns_exporter_1 }}"
          port: 9617
        - name: speedtest
          ip: "{{ ip_speedtest_exporter }}"
          port: 9798
        - name: ntp-exporter
          ip: "{{ ip_ntp_exporter }}"
          port: 9123
        - name: nginx-exporter
          ip: "{{ ip_nginx_exporter }}"
          port: 4040
        - name: pve-exporter
          ip: "{{ ip_pve_exporter }}"
          port: 9221
- name: Install nginx exporter
  hosts: vm0.nibbler
  roles:
    - role: nginx_exporter
      become: true
      nginx_exporter_network: "{{ 'vlan-' + vlan_management.name }}"
      nginx_exporter_ip: "{{ ip_nginx_exporter }}"
