---
# Default variables for prometheus

# Scraping jobs
prometheus_jobs: []
# - name: job name
#   scrape_interval: 15s (default)
#   metrics_path: /metrics (default)
#   static_configs:
#     - targets: [ "192.168.1.2:8000" ]

prometheus_network: default
prometheus_ip:
prometheus_grafana_network: default
prometheus_grafana_ip:

prometheus_grafana_user: admin
prometheus_grafana_password: admin
prometheus_grafana_org: Main Org.

prometheus_version: 2.53.1
